spring.data.mongodb.uri=mongodb://localhost:27017/boutiqueDB
spring.data.mongodb.database=boutiqueDB
app.jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuMTIzNDU2
app.jwt.expiration-ms=604800000

# Image Upload Configuration
app.upload.dir=uploads/images
app.upload.max-size=5242880

# Server Configuration
server.servlet.context-path=/
server.port=8080